theme: jekyll-theme-hacker
title: Morgan[ism] Sziraki
description: A clean and well lighted place for shameless self promotion


plugins:
  - jekyll-admin
  - jekyll-gist
  - jekyll-coffeescript

# Enable safe mode
safe: true

# Whitelist plugins under safe mode.
# Note that `some-other-jekyll-plugin` is not listed here. Therefore,
# it will not be loaded under safe mode.
whitelist:
  - jekyll-admin
  - jekyll-gist
  - jekyll-coffeescript

jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration
  homepage: "pages"

